### ISSUE TITLE
Dockerfile will not build

### ISSUE THREAD

**Issue by magno32** [TIBCOSoftware/jrio-docker#4]
The jetty dependency is missing...  So it punts there.  Looks like `base` is also missing.

**Comment by teodord** [comment]
Hello,

This project here on Github contains the Dockerfile that can be used to build the Docker image out of a JasperReports IO Professional binary distribution which can be obtained from Tibco Software.
https://www.jaspersoft.com/download

Indeed, it probably needs to be updated as it is not in sync with the latest JasperReports IO Professional version 2.0.0.

But since you already need to download the product from the Tibco Software customer portal, you would find an up-to-date version of the same Dockerfile inside the /docker folder of the ZIP archive.
And you should be able to successfully build the Docker image out of that binary distribution that you download.

I hope this helps,
Teodor
